### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by paintfrussianblue** [1113pmoc/project#12]
- Ability to integrate Facebook account for easy sign-up
- Details such as name (and profile photo?) can be used

**Comment by jeffreyleeon** [comment]
For firebase application
- Follow the steps in https://firebase.google.com/docs/auth/web/facebook-login

**Comment by hmwongak** [comment]
Register and get AngularJS SDKs and APIs for Facebook Login and manage account setting on Facebook Developer Web
